### ISSUE TITLE
(Request) Add an option to use the new rebrand colors/"Clyde" logo for the people that prefer it

### ISSUE THREAD

**Issue by NWinXP** [Marda33/SkeuoCord#11]
I would like to see an option to use the new Discord rebranding. Sure, most users hate the new branding, but there are some people who think otherwise. I would like to see this as a separate CSS file from the base named "SkeuoCordBrandingExpirement.css" with instructions to use this file instead in the README.md file (repo description).

**Comment by Marda33** [comment]
There's now a non-brand color replacing version avaible in the repo.
