### ISSUE TITLE
The background gradients are raw images and not CSS linear-gradient

### ISSUE THREAD

**Issue by pie-flavor** [Marda33/SkeuoCord#12]
I imagine it'd be quite a large amount of work to make it otherwise, but the lack of it contributes both to RAM usage and inflexibility with resizing.

**Comment by Marda33** [comment]
I've done my best to compress non-CSS gradients to reduce file size, and the resulting files are about as large as any other image resource I use witin SkeuoCord, so I don't think that would pose much of a problem now. I may look into replacing them with proper CSS gradients in the future.
