### ISSUE TITLE
Support for In-App Notifications?

### ISSUE THREAD

**Issue by pie-flavor** [Marda33/SkeuoCord#13]
[Link to plugin](https://github.com/1Lighty/BetterDiscordPlugins/tree/master/Plugins/InAppNotifications)
The notifications from IAN are the only things not skeuified in my setup, and I'd love it if they were.

**Comment by Marda33** [comment]
Support has now been added for this plugin. Reload SkeuoCord 5-10 minutes from now to recieve the update.
