### ISSUE TITLE
Some Feedback/Suggestions for Improvement

### ISSUE THREAD

**Issue by ALIENINATOR** [Marda33/SkeuoCord#14]
Hi, thanks for making this skeuomorphic design! I really like it, we need more skeuomorphism back in the tech world. I never liked the flat look or the even worse material design Google replaced flat with. But it was the recent Discord update that corporatized the logo and turned the ui into a joke that led me to try out custom themes.

Anyway, the gradients, shadows, and 3D button everywhere are much appreciated, but the theme could be better. For example, when I click on  a Discord server, I still get that little line next to the side of the icon. For a more authentic skeuomorphism feel, could you alter the look so that each server icon looks like a 3D icon, and clicking on the icon makes it look like the button is pressed down, rather than changing from circle to square and getting a line on the side of the icon?

Additionally, the hover over image for some buttons could use a little more contrast. For example, hovering over the minimize/maximize buttons at the top corner just makes them slightly more grey. More color difference/contrast between normal and hovered-over/clicked would make it even easier on the eyes. This is true for other buttons, like reshare as well.

But overall, I'm really loving the look! Much better even then the original Discord ui.

**Comment by Marda33** [comment]
The way server icons are themed in Discord wouldn't allow for your first suggestion to happen as the server icon goes on top of whatever effects you apply to the base icon itself. 
Could you tell me more about how you'd want hover-pressed states of buttons to be changed?

**Comment by Silithas** [comment]
2 suggestions:

1: Make the highlight on a comment more subtle to just indicate you're hovering over it to be a bit more pleasant.
2: Make the squares of comments and profile pictures have more bevel to look smoother and not so sharp in the corners.
