### ISSUE TITLE
Channel width bar.

### ISSUE THREAD

**Issue by Krazytrain** [Marda33/SkeuoCord#18]
Hey i cant seem to change the width to 240px i think right now its at 220px. How would i change the width of the bar?

**Comment by Krazytrain** [comment]
Any help with this? I cant seem to find your discord help server too.

**Comment by Marda33** [comment]
The channel scroller is 237 pixels wide if that's what you meant, and you can paste this in the theme file or in Custom CSS to change the width:
.sidebar-2K8pFh, .sidebar-2K8pFh.theme-dark {
	width: 240px !important;
}
Also add this to make server banners resize accordingly:
.theme-dark .bannerImage-3KhIJ6, .sidebar-2K8pFh.theme-dark .bannerImage-3KhIJ6, .theme-light .bannerImage-3KhIJ6 {
	width: 240px !important;
}
