### ISSUE TITLE
"BOT" label looks a bit off

### ISSUE THREAD

**Issue by Radioo** [Marda33/SkeuoCord#21]
![image](https://user-images.githubusercontent.com/9533160/147904816-4b003547-a1f8-44ad-9dec-054e9a42408f.png)
Looks like the bottom portion is slightly cut off.

**Comment by Marda33** [comment]
This issue should now be fixed with the recent update. I've been getting different results on browser and desktop, so let me know if it's been resolved for you.

**Comment by Radioo** [comment]
Yes! That seems to have done the trick.
