### ISSUE TITLE
Newest Canary update broken

### ISSUE THREAD

**Issue by Lannuked** [Marda33/SkeuoCord#22]
I updated my canary, and it appears the theme isn't fully loading everywhere. The discord logo on the top left goes blank, user icons are square in profiles and the member list, but not the chat. Few menus have skeuomorphic styling.

**Comment by tersiswilvin** [comment]
It looks like it's now broken even on stable discord.

**Comment by Marda33** [comment]
I’m aware of the issues that came with the new update. I’ll try to push a fix ASAP whenever I find enough free time.

**Comment by marioman63** [comment]
Reading other theme developers, it appears that Discord changed all the CSS class names. I ran the CSS file through a script that auto-converted a decent amount of them and attempted to do more manually but I don't know enough about the class names to find all the relevant ones (such as any to do with the chat input, mute/deafen controls, minor parts of the header/window control buttons and the options screen BG).

**Comment by Marda33** [comment]
Considering the sheer amount of class changes, I’ll push fixes in parts until I get everything mostly working again. I was able to mostly fix chat UI theming yesterday before the update came to stable, I’ll try to push that later today.

**Comment by Lannuked** [comment]
Take your time if needed, I don't instantly need a fix lol.

**Comment by Marda33** [comment]
Managed to fix the major issues after running the file through a theme fixer script. I'll continue work to fix the minor issues, let me know here if you find any.

**Comment by tersiswilvin** [comment]
I did find a button still ineffective when applying the theme under account removal in settings.
![unknown](https://user-images.githubusercontent.com/52929976/149010428-6f91d928-d91b-477e-a597-afd01357414c.png)

**Comment by Marda33** [comment]
The most recent update should fix button theming alongside some other bugs.

**Comment by marioman63** [comment]
at least in light mode, i don't see any issues. i still have the previous release on a laptop so i can compare with it if i find anything. Thanks for the quick update, this is easily my favourite theme for Discord by far!
