### ISSUE TITLE
Read All Notifications Button

### ISSUE THREAD

**Issue by ModelVex001** [Marda33/SkeuoCord#23]
I use this Read All Notifications Button plugin (ReadAllNotificationsButton found here https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/ReadAllNotificationsButton/) and it has the circle and then square around it as if it was a server and that being there is preventing me from being able to click the button to read all notifications. I was wondering if you could somehow get around that so the circle and square can be there for the servers but NOT the button that way the button will work but if not at least put a toggle for the feature so we can choose to enable/disable it
![Screenshot 2022-04-13 230904](https://user-images.githubusercontent.com/103619259/163306444-5c382413-618b-4525-8163-8765ed5b67bc.png)
.

**Comment by Marda33** [comment]
I won’t have access to my computer for a while, so I can’t do anything at the moment. I’ll get to the issue when I get access again.

**Comment by Marda33** [comment]
This issue has now been fixed in the new version.
