### ISSUE TITLE
Reactions missing CSS

### ISSUE THREAD

**Issue by marioman63** [Marda33/SkeuoCord#25]
[The reaction icons below a message seem to be missing CSS](https://cdn.discordapp.com/attachments/407377861901811733/979185900087050400/unknown.png), making them stand out from the rest of the theme. This seems to occur with both dark and light versions of SkeuoCord. In the above image, notice how both reactions that I used and reactions from other people seem to match the default light theme of Discord.

**Comment by Marda33** [comment]
I’m busy with studies and will be until late June, so I can’t push a fix right now. I’ll get it fixed when I find time.

**Comment by Marda33** [comment]
This issue is now fixed in version 1.23.1.
