### ISSUE TITLE
[Feature Request] Make the new profile cards consistent with the theme, please?

### ISSUE THREAD

**Issue by Emmasworld** [Marda33/SkeuoCord#26]
Pretty much what the title says - they've added new nitro themes to the profile cards, nobody I know is using them yet (and I have the setting to show them disabled anyways, it's an accessibility thing where you can make the cards stay with the default discord appearance but I have it set just because they're completely unnecessary in my opinion and I don't want to see the 5,000th crappy eyesore gradient between like ten different colours once people do start using them.)

But basically, the themeless/default profile cards don't look consistent with the rest of the theme, and as a result it winds up looking kind of odd. Perhaps make them kind of resemble the contact card popups of Windows Live Messenger, if you've ever seen that? I think that'd look neat.

**Comment by Marda33** [comment]
Could you show what this profile card theming feature looks like? I don't seem to have it enabled on my client yet.
As for redesigning the profile card, what parts do you think break consistency between them and the rest of the theme? I'd appreciate a mockup of what you think looks better for them as well since I haven't really thought of changing their design.

**Comment by Emmasworld** [comment]
Oh, here's what they look like, both with and without Skeuocord enabled.
![with Skeuocord](https://user-images.githubusercontent.com/48417442/187615388-5d3a6f78-1b90-438a-9790-0d80d1627f28.png)
![without Skeuocord](https://user-images.githubusercontent.com/48417442/187615406-1de789c3-1ac5-488c-80c7-18310c71b3b3.png)

**Comment by Marda33** [comment]
I’ll get to work on these as soon as either if I can find a way to force them on my client or they get enabled on there if I can’t.

**Comment by Marda33** [comment]
SkeuoCord now has proper theming for the new non-themed and themed profile cards with version 1.29. Let me now if you find any further issues.
