### ISSUE TITLE
I'd love to see this on Aliucord

### ISSUE THREAD

**Issue by logan-0712** [Marda33/SkeuoCord#27]
Hello! I don't expect this to be comfortably possible with the android version of discord going through so many changes right now, but an Aliucord version of Skeuocord would be fantastic <3 Aside from the request, this is the most comfortable discord theme I've used yet, thanks so much.

**Comment by Marda33** [comment]
From what I know, the mobile versions of Discord are built in a completely different way that don’t allow full CSS theming to work (save for simple color and font changes); so this is impossible. 
Even if it was, I don’t have a new enough Android device to test it with; so unfortunately I can’t do this. Do let me know if I’m wrong in the first matter though.
