### ISSUE TITLE
Profile pictures disappear

### ISSUE THREAD

**Issue by zeffdakilla** [Marda33/SkeuoCord#28]
I love this theme so much! It's completely working besides this one tiny glitch. It's not too big of a problem, but when someone starts typing their profile picture disappears and won't show again until you reload the page.
![image](https://user-images.githubusercontent.com/111836537/198507127-8bfdd708-b760-48fa-8ac7-333ebca474af.png)
![image](https://user-images.githubusercontent.com/111836537/198507152-b0b41441-052e-4cd5-9e6f-fc5cbf5cb05e.png)

**Comment by Marda33** [comment]
Turns out that was just a minor oversight in the code. This issue has now been fixed in version 1.29.5, along other fixes and improvements.
