### ISSUE TITLE
Will custom icons ever be a thing later in this theme's lifespan?

### ISSUE THREAD

**Issue by connor148** [Marda33/SkeuoCord#3]
I love this theme and would love to see some custom icons and graphics for discord based off of late 2000's emoticon design!

**Comment by Marda33** [comment]
Discord uses SVG's for in-app icons, which aren't replaceable AFAIK. For the taskbar ping notification/tray icons; I tried changing them but upon launch, the custom icons get replaced with the original versions, so sadly those aren't replaceable either.
