### ISSUE TITLE
[Possible oversight?] When highlighting someone's icon to view full profile, dark shape displays as a circle instead of the intended square.

### ISSUE THREAD

**Issue by Emmasworld** [Marda33/SkeuoCord#31]
Pretty much the title - if someone has a custom server profile, and you select them and hover over their icon and bring up the "view profile" option, the darkened shape that is meant to appear overtop their icon is a circle rather than a square, and as a result, looks a bit strange.

Weirdly, this wouldn't display on my own profile card, so I had to use the card of someone else in the server for this picture. (perhaps because I don't have Nitro and as such don't have a server profile like this? so it might just be related to the ability to have multiple profile pictures or something. I dunno, I'm not a developer or anything. :shrug:)

![image](https://user-images.githubusercontent.com/48417442/210046501-16b93233-2176-4e8c-8315-dfda951af1aa.png)

**Comment by Marda33** [comment]
From what I’ve seen, this only happens on profiles with the limited time Christmas overlays. I didn’t touch on the issue since the feature is going away soon but I could push a quick fix when I find time.

**Comment by Marda33** [comment]
This issue should now be fixed.
