### ISSUE TITLE
Performance impacting?

### ISSUE THREAD

**Issue by Impeta** [Marda33/SkeuoCord#32]
Could be just  on my end, but your theme, and the only one, makes my Discord client slugs out on its entirety. Takes few more seconds for changing through servers and their channels, as well opening options. I have a relatively modern computer.

**Comment by Marda33** [comment]
SkeuoCord does have a small impact on performance from my experience as well, but it shouldn’tve gotten to that point. 
How many plugins do you have enabled? A high amount could lag the client with the theme enabled.

**Comment by Marda33** [comment]
And only SkeuoCord consistently hampered performance with all these client mods? I only have used BetterDiscord so I wouldn't know if the theme has some kind of issue with the other client mods/plugins on those mods. 
This is the first time I've recieved such a performance issue as well (and SkeuoCord doesn't lag at all when you apply it on the webapp via a CSS styling extension for example), so maybe there's something on your end?

**Comment by Marda33** [comment]
Just as a test, does this version have any change in lag? This has all the base64 encoded image resources embedded within the theme removed. They're small in size, but there's plenty of them. I suspect these could be causing lag, otherwise I have no idea.
https://raw.githubusercontent.com/Marda33/SkeuoCord/master/updates/SkeuoCord_Nobase64.theme.css

**Comment by cyan-2048** [comment]
could this be that your hardware acceleration settings are breaking things?

**Comment by Marda33** [comment]
I'll close this issue for the time being since there's no appearent specific cause for the lag. I'll try to optimize the theme as much as possible in future versions.

**Comment by theOneTrueFunniBoi** [comment]
I have this same exact issue, only this theme in particular lags. Only difference is that I'm running Windows 11 Home, not Linux.
