### ISSUE TITLE
status indicators

### ISSUE THREAD

**Issue by ilkehylke** [Marda33/SkeuoCord#33]
a suggestion that came to my mind is that you do something to the status indicators (online, idle, dnd), because they don't really fit the theme, at least in my opinion
![image](https://user-images.githubusercontent.com/34130711/215366853-5b0cb9dd-9f77-4b04-bd74-5bd7c115b7d3.png)

**Comment by Marda33** [comment]
Unfortunately status indicators are not themable, as far as I've tried. 
The most I could do was add dropshadows, which didn't look good and weren't in a usable state.
