### ISSUE TITLE
file icons need to be changed

### ISSUE THREAD

**Issue by WebFreak001** [Marda33/SkeuoCord#34]
very low contrast between file icon and background + file icon doesn't fit that well into the design

![sample file sent on discord](https://wfr.moe/f6qgKc.png)

The light blue kind of bleeds into the gradient background.

**Comment by Marda33** [comment]
I won't be changing Discord's SVGs as that would further bloat the theme. I'll add dropshadows to icons to fix the contrast issues in the next update.
