### ISSUE TITLE
Tab styling (view profile)

### ISSUE THREAD

**Issue by WebFreak001** [Marda33/SkeuoCord#35]
The tabs here could maybe use a small overhaul in terms of styling and spacing:

![view profile on user in discord](https://wfr.moe/f6qv1s.png)

**Comment by Marda33** [comment]
How do you think the tabs should be overhauled? I can't see much to do with them other than reducing the height of the tab items.

**Comment by WebFreak001** [comment]
maybe the tabs could be made similar to look like old IE8 tabs?

![image](https://user-images.githubusercontent.com/2035977/220732019-c0f7307f-71c7-4f2a-a39e-9709ef1374d6.png)

**Comment by Marda33** [comment]
What do you think of this styling?
![image](https://user-images.githubusercontent.com/60007477/220746364-8b54e4d3-4f54-4a55-87c0-10f3ef5e9990.png)
![image](https://user-images.githubusercontent.com/60007477/220746402-ac889d45-a034-41c6-bc0a-20a8492ca93b.png)

**Comment by WebFreak001** [comment]
love it

**Comment by Marda33** [comment]
This style has now been implemented in the current version.
