### ISSUE TITLE
Unread indicator has uncomfortable margins in compact mode

### ISSUE THREAD

**Issue by francinum** [Marda33/SkeuoCord#38]
The unread indicator's margins aren't adjusted for compact mode, resulting in it taking up an entire line's worth of space when it shouldn't, causing awkward layout shifts.

Themed
![image](https://file.house/qVmN.png)
Unthemed
![image](https://file.house/hv8f.png)

**Comment by Marda33** [comment]
Margins for compact mode should now be adjusted properly in the new version. Let me know if they're fine for you.

**Comment by francinum** [comment]
Version key
![img](https://file.house/N6rP.png)
Old
![image](https://user-images.githubusercontent.com/5572280/233489728-1071dfdf-9831-4c57-bce0-51c1e383a200.png)
New
![img](https://file.house/pijU.png)

Looks good, Personally I'd prefer the unread indicator have near-zero height like the speaker divider, but this is still far more comfortable.
