### ISSUE TITLE
"Discover" page has a bit that remained unchanged by the theme, making it hard to read.

### ISSUE THREAD

**Issue by waterdrinkingfox** [Marda33/SkeuoCord#39]
![image](https://user-images.githubusercontent.com/112423658/235373518-3b6ee5fa-8506-46f3-be4b-b0ea96eeb852.png)

Dark mode

![image](https://user-images.githubusercontent.com/112423658/235373535-438f7530-96f2-415f-a0ca-0dbf5bd51c18.png)

Light mode

Edit: I have other themes enabled too, but they aren't the source of the problem.

**Comment by Marda33** [comment]
This issue has been fixed in the new update.
