### ISSUE TITLE
Prompt (?) messages look very off [CANARY]

### ISSUE THREAD

**Issue by PF94** [Marda33/SkeuoCord#4]
![image](https://user-images.githubusercontent.com/45898787/86550521-98abcf80-bf10-11ea-83e8-731fb9330c0f.png)
![image](https://user-images.githubusercontent.com/45898787/86550534-a19ca100-bf10-11ea-8208-9f7bb546642f.png)

This issue affects "Set/change nickname" and "Server join" prompts.

I don't know how it happens, but i think it's something to do with spritesheets.

This issue might have occured sometime between vBuild 4074 (early-June) to vBuild 5854 (early-July). I don't know the exact version since I've just updated SkeuoCord today.

**Comment by Marda33** [comment]
This issue will be fixed once the changes roll out to the main app.
