### ISSUE TITLE
[Request] Please make it compatible with BlurpleRecolor

### ISSUE THREAD

**Issue by candyunicorn33** [Marda33/SkeuoCord#41]
I have set a custom accent color that should change the color of the Discord logo of the Direct Messages button and bot tags and "Add to server" buttons. However Skeuocord overwrites them with the blue stuff.
Thanks.
[https://github.com/mwittrien/BetterDiscordAddons](https://github.com/mwittrien/BetterDiscordAddons)

**Comment by Marda33** [comment]
I've made a separate recolor theme import to not conflict with the theme's normal appearance. Everything except the image gradients I couldn't easily change should be working now.
In SkeuoCord.theme.css, replace "SkeuoCordBase.css" with "SkeuoCord_Recolor.css" or "SkeuoCord_Recolor_CustomBG.css" if you also want to use a custom background image.
Let me know if it works for you.

**Comment by candyunicorn33** [comment]
It works wonderfully :) Super appreciate it
