### ISSUE TITLE
Server Subscriptions-exclusive channels cause layout shift on mouseover

### ISSUE THREAD

**Issue by francinum** [Marda33/SkeuoCord#42]
![](https://file.house/P9sP.gif)

```
SkeuoCord 1.34.5
Host 1.0.9013(34160)
Stable 210566(fc3ede1)
```

**Comment by Marda33** [comment]
I pushed an update to try to fix the issue, I don't have access so server subscriptions where I'm located. 
Has that fixed the issue for you?

**Comment by Marda33** [comment]
The newest update should have fixed this issue I believe. Let me know if that's the case.

**Comment by francinum** [comment]
Perfect
