### ISSUE TITLE
Soundboard button

### ISSUE THREAD

**Issue by andrwcrr** [Marda33/SkeuoCord#43]
Any chance you can make the soundboard button not have the music notes cut off?
![image](https://github.com/Marda33/SkeuoCord/assets/128940455/1d4434e5-ea80-4c29-9cdd-57e065e0dfa5)
Example (Default dark theme):
![image](https://github.com/Marda33/SkeuoCord/assets/128940455/08a25316-2070-4e0a-aa0a-29e718827baf)

**Comment by Marda33** [comment]
This issue has been fixed in the new version. It should go live in a couple of minutes, reapply the theme then to get the update.
