### ISSUE TITLE
Multiple Layout Issues

### ISSUE THREAD

**Issue by francinum** [Marda33/SkeuoCord#44]
Appear to be related to a new discord update?
![](https://file.house/dF-C.png)
![](https://file.house/lI5_.png)

```
SkeuoCord 1.34.5
Host 1.0.9015(34898)
Stable 213459(97e5bed)
```

**Comment by Marda33** [comment]
The newest update should've fixed those issues now. I don't have the attachment button issue here though, could be something on your end?
