### ISSUE TITLE
user profiles overlap each other on the vc/screenshare preview for servers

### ISSUE THREAD

**Issue by GentlemanMC** [Marda33/SkeuoCord#45]
![image](https://github.com/Marda33/SkeuoCord/assets/76640636/e72f3e36-a3d3-4f0f-8d48-5c93d882949d)

**Comment by Marda33** [comment]
This isn't really a bug, that's how the stacked profile pictures look with the SVG mask removed and I chose to keep them that way.
Would you be fine with backgrounds getting added for PFPs with transparency for them to not blend in, or would you rather have them separated still if that's doable?

**Comment by GentlemanMC** [comment]
i think having backgrounds would look nicer than being separated

**Comment by Marda33** [comment]
Stacked PFPs have backgrounds now in the new update. Let me know if I missed any other stacked PFP classes.
Before:
![image](https://github.com/Marda33/SkeuoCord/assets/60007477/b89641a8-62d5-4761-965f-5ac4f6aa26da)
Now:
![image](https://github.com/Marda33/SkeuoCord/assets/60007477/6584c666-cb67-4bde-890c-24ed229b83f0)

**Comment by GentlemanMC** [comment]
U can close this now if u want
