### ISSUE TITLE
Discord Nitro avatars in call aren't the right size

### ISSUE THREAD

**Issue by lentilcorvid** [Marda33/SkeuoCord#46]
skeuocord (top 2 are nitro avatars)
![image](https://github.com/Marda33/SkeuoCord/assets/141605997/2906782d-be4d-4847-9cb2-2039f1852cb4)
vanilla discord theme
![image](https://github.com/Marda33/SkeuoCord/assets/141605997/b5dfa339-6297-4c90-af41-d9a61dd09742)

**Comment by Marda33** [comment]
By “nitro avatars” do you mean animated/GIF avatars?

**Comment by lentilcorvid** [comment]
those might not work properly too, but i was specifically talking about the server-specific avatars you can get with nitro

**Comment by Marda33** [comment]
I've pushed a update to try to fix the issue. Does it work for you?

**Comment by lentilcorvid** [comment]
absolutely based thank you so much
