### ISSUE TITLE
Frutiger Aero

### ISSUE THREAD

**Issue by LualtOfficial** [Marda33/SkeuoCord#47]
I know this is not exactly that the issues tab is for but this is the only way to contact you without going straight into your dms.
Are you please able to make a frutiger aero theme? And if not do you know if there exists one that i could use? Thanks in advance :)

**Comment by Marda33** [comment]
I unfortunately don’t have the time to make and maintain a new theme from stratch due to my studies starting soon. 
I think [DTM-08 by 11pixels](https://betterdiscord.app/theme/DTM-08)  should be similar enough to what you want, as it’s a glossier skeuomorphic theme.

**Comment by LualtOfficial** [comment]
Thats understandable thank you so much!
