### ISSUE TITLE
Theming broken in chats after latest discord update

### ISSUE THREAD

**Issue by Vulpovile** [Marda33/SkeuoCord#48]
![image](https://github.com/Marda33/SkeuoCord/assets/19483545/aa3f2e9d-6391-45a9-a1ad-c54e33fa1f36)
![image](https://github.com/Marda33/SkeuoCord/assets/19483545/2ab18cc7-ac41-4094-b415-5614c6fa33f6)

This is using combined light mode + dark sidebar. Issue happens in both individual/group chats as well as server chats

That being said, it's *fairly minor*, but still.

**Comment by Vulpovile** [comment]
![image](https://github.com/Marda33/SkeuoCord/assets/19483545/97707e87-e517-4a14-8cea-d202745fc7ce)
Embeds and images as well as hovering still looks right

**Comment by xxHAKRxx** [comment]
I've been getting that too. Guess I'll have to use Time Machine 2008 until this is fixed.

**Comment by Marda33** [comment]
The current version (which'll be live in a couple minutes) should've fixed the issues now. Let me know if you come across something I missed.

**Comment by Vulpovile** [comment]
Seems good! Thanks a ton, this is an awesome theme!
