### ISSUE TITLE
Discord quietly broke all themes

### ISSUE THREAD

**Issue by Altarya** [Marda33/SkeuoCord#49]
As reported [here](https://github.com/Vendicated/Vencord/issues/1838), Discord quietly pushed an update about ten hours ago that completely broke pretty much all themes and most BD or Vencord plugins

**Comment by Marda33** [comment]
I've uploaded partially fixed versions of the import files which should restore most of the theming. After things get further figured out with this update, I'll work on fully fixing the remaining issues.

**Comment by Altarya** [comment]
Seems like only a few minor things are broken, thanks!
