### ISSUE TITLE
Can you add a home button variable?

### ISSUE THREAD

**Issue by SSadako** [Marda33/SkeuoCord#50]
I would like to change the home button but idk where/what element to edit.

**Comment by Marda33** [comment]
Adding
```
.tutorialContainer__890ea .wrapper_d281dd .childWrapper__01b9c {
    background: url(linkhere) center/cover no-repeat !important;
}
```
to the end of SkeuoCord.theme.css should override the default image. Let me know if it doesn't.

**Comment by SSadako** [comment]
> Adding
> 
> ```
> .tutorialContainer__890ea .wrapper_d281dd .childWrapper__01b9c {
>     background: url('linkhere') center/cover no-repeat !important;
> }
> ```
> 
> to the end of SkeuoCord.theme.css should override the default image. Let me know if it doesn't.

Thanks!! It works. (I was doing the same thing though I didn't put it in the end of the css 😔)

**Comment by SSadako** [comment]
> Adding
> 
> ```
> .tutorialContainer__890ea .wrapper_d281dd .childWrapper__01b9c {
>     background: url('linkhere') center/cover no-repeat !important;
> }
> ```
> 
> to the end of SkeuoCord.theme.css should override the default image. Let me know if it doesn't.

![image](https://github.com/Marda33/SkeuoCord/assets/66819431/5233bae1-bdad-4697-906d-0e8bc1b49361)
What's about the blue corners? Thanks for replying though

**Comment by Marda33** [comment]
Version 1.35 should've fixed this issue. Let me know if it didn't.
