### ISSUE TITLE
No Transparency On Images Preview

### ISSUE THREAD

**Issue by BHY4A** [Marda33/SkeuoCord#51]
Appears that theres no transparency on images preview with theme turned on. No plugins turned on.

![2023-10-27 191119](https://github.com/Marda33/SkeuoCord/assets/33008019/68a87ab6-e22a-4c8d-b4d5-6d85b25e5ce0)
![2023-10-27 191052](https://github.com/Marda33/SkeuoCord/assets/33008019/64572d7f-44dd-4ff0-b77d-a5f6d31a51ed)

**Comment by francinum** [comment]
This only occurs for multi-image message previews, the ones that let you tab between images:

![](https://file.house/Lom4.png)

![](https://file.house/OK75.png)
![](https://file.house/XeKR.png)

**Comment by Marda33** [comment]
This issue has been fixed in version 1.35 alongside other minor issues leftover from the class reroll. Disable and reeanable the theme in a couple minutes to get the update.
