### ISSUE TITLE
"Read all" button plugin does not work well with this theme

### ISSUE THREAD

**Issue by xxHAKRxx** [Marda33/SkeuoCord#55]
![image](https://github.com/Marda33/SkeuoCord/assets/140458341/8fb434ab-884a-462a-8114-c07a7dc531ff)
I dunno which plugin is at fault for this bug, but my most likely guess is the Skeuocord theme cuz this plugin works fine on other themes

**Comment by Marda33** [comment]
This issue has been fixed in the new update along with fixes for PluginRepo and ThemeRepo. Sorry for taking a while.
