### ISSUE TITLE
Server icons disappear on hover

### ISSUE THREAD

**Issue by Vulpovile** [Marda33/SkeuoCord#56]
![image](https://github.com/Marda33/SkeuoCord/assets/19483545/5784bcbc-682e-4acb-b652-e97d9500ad8c)

Steps to reproduce:

1. Enable Theme
2. Hover mouse over server icon
3. Move mouse off server icon

**Comment by Marda33** [comment]
Does this only happen on the webapp for you? On my end I can only replicate this issue when theming the website with Stylus.

**Comment by Vulpovile** [comment]
Just tried, this happens when I try Vencord/Vesktop which uses the Webapp, but BetterDiscord appears to work just fine with it

**Comment by Marda33** [comment]
I've looked through all the code that themes the server icons and modifying/removing them doesn't remove the issue. I'll look further into the issue later to see if it's fixable on my end.

**Comment by Marda33** [comment]
After further testing, this issue only seems to happen on Chromium-based browsers while Firefox and its derivatives don't seem to have it. 
Unfortunately it doesn't seem like something that can be fixed on my end for now, so I'll be closing the issue. Should I find a fix, I'll update the import immediately.

**Comment by MysticAx0lotl** [comment]
This is an issue with Electron-based Discord clients (pretty much all desktop clients) as well. I tested using ArmCord and had the same problem

**Comment by Marda33** [comment]
Chrome 121 seems to have fixed the issue on my end. Could you check too?

**Comment by MysticAx0lotl** [comment]
Great! I will test this asap

**Comment by MysticAx0lotl** [comment]
Works for Vesktop, I will test ArmCord later

**Comment by MysticAx0lotl** [comment]
Works with ArmCord!

**Comment by Vulpovile** [comment]
Confirmed it works on Vesktop as well
