### ISSUE TITLE
server icons disappear when hovered over

### ISSUE THREAD

**Issue by end3rguy** [Marda33/SkeuoCord#57]
they only reappear when you restart discord

**Comment by ShiiroSan** [comment]
Surely linked to https://github.com/Marda33/SkeuoCord/issues/56

**Comment by Marda33** [comment]
Chrome 121 seems to have fixed this issue on my end. Could you also check on your end?

**Comment by Marda33** [comment]
I've also pushed an update that should fix the issue on other clients. Let me know if it hasn't.

**Comment by ShiiroSan** [comment]
> Chrome 121 seems to have fixed this issue on my end. Could you also check on your end?

Can confirm it works with Vencord for me. Don't really know which Chrome version they use.
