### ISSUE TITLE
reduce opacity in SkeuoCord_BGImport

### ISSUE THREAD

**Issue by AidanMullis524** [Marda33/SkeuoCord#58]
Needs a version to reduce the opacity of the background in text channels and the text message hover in SkeuoCord_BGImport, bringing it closer to the options menu would look really great.

**Comment by Marda33** [comment]
I've made a new version of BGImport which increases transparency in the chat background and message hovers as you suggested.
 Replace `SkeuoCord_BGImport` in your theme import with `SkeuoCord_BGImport_ExtTransp` to use it. Is it fine for you?

**Comment by AidanMullis524** [comment]
yes that is perfect, thank you very much
