### ISSUE TITLE
Vencord deleted messages style

### ISSUE THREAD

**Issue by bigfoot547** [Marda33/SkeuoCord#60]
Hello. I'm using Vencord with this theme, and was wondering if you could make the deleted messages have a similar style to messages where you're mentioned. Here's now it looks now (first message is not deleted and mention, second message is deleted and mention, third is just deleted):

![image](https://github.com/Marda33/SkeuoCord/assets/21959175/278429d7-a814-4949-bcd1-b666ee70e687)

The class name for deleted messages is `messagelogger-deleted` on the message list item:

![image](https://github.com/Marda33/SkeuoCord/assets/21959175/d73b598a-7432-4e63-9792-e6dd29a4d380)

Thank you!!!

**Comment by Marda33** [comment]
I don't support message logger tweaks.
