### ISSUE TITLE
Theme no longer applies to majority of UI

### ISSUE THREAD

**Issue by francinum** [Marda33/SkeuoCord#61]
![image](https://github.com/Marda33/SkeuoCord/assets/5572280/bfaab0a1-1040-47d8-a1c5-4d9435634de9)

```
SkeuoCord 1.35.3

stable 279382 (5c40119)
Host 1.0.9037 x86 (45369)
Windows 10 64-bit (10.0.19045)

Vencord De9122b
```

**Comment by toydotgame** [comment]
Can confirm also on a different machine:
![image](https://github.com/Marda33/SkeuoCord/assets/64190512/3d796419-dff7-40d9-85a4-8b4a49fa42bd)

(If it's the case that Discord has refactored and changed all of its element class names…I wish you godspeed)

**Comment by 90sdiablo** [comment]
I'm also facing the same issues and heard the announcement from the Vencord Discord server. I hope you can fix the theme real soon. <3

**Comment by Marda33** [comment]
I’m aware of the issue, however it’s not clear the class reroll will stick and I’ll be busy with uni projects for a while. If the class changes don’t get reverted I’ll push an update as soon as possible.

**Comment by 90sdiablo** [comment]
> I’m aware of the issue, however it’s not clear if the class reroll will stick and I’ll be busy with uni projects for a while. If the class changes don’t get reverted I’ll push an update as soon as possible.

Cool beans! ^^ Can't wait if you need to fix it.

**Comment by textstack** [comment]
![lobster](https://github.com/Marda33/SkeuoCord/assets/46581273/313bb8c4-802f-40c8-b53a-1c14ab716f80)

**Comment by sumhex151** [comment]
same thing, discord feels so weird without this beautiful theme

**Comment by 90sdiablo** [comment]
I'm not seeing anything get reverted. Please update the code when you have the chance. <3

**Comment by Marda33** [comment]
Version 1.36 should've fixed everything major. Let me know if I've missed anything.
