### ISSUE TITLE
Guild icon rim missing

### ISSUE THREAD

**Issue by francinum** [Marda33/SkeuoCord#64]
![image](https://github.com/Marda33/SkeuoCord/assets/5572280/c5bdb26f-0369-4dbe-bc51-9f6b287325f7)

Moused-over guilds are permanently expanded to square.

Skeuocord 1.36.2

Stable 301920 (198d4c4)
Vencord 4ec01d0 (Standalone)
Host 1.0.9149 x64 (48589)

**Comment by Marda33** [comment]
This issue along some others have been fixed in version 1.36.3.
