### ISSUE TITLE
Not functional anymore?

### ISSUE THREAD

**Issue by homebromchambone** [Marda33/SkeuoCord#65]
Latest discord update seems to have broken it on my end with Vencord. Can anyone confirm it is broken for you as well?

**Comment by Tanglingbat06** [comment]
Same with me too, I think the latest Discord update broke the theme.

**Comment by derpguy125** [comment]
Definitely. The amount of Vencord plugins that were also broken by the latest update I can't even count on my hands.

**Comment by skall0900** [comment]
Same issue here.

**Comment by textstack** [comment]
![lobsterer](https://github.com/Marda33/SkeuoCord/assets/46581273/7c301bad-d916-4efe-9d06-0e8b37c3af6e)

**Comment by Marda33** [comment]
Everything should be fixed in the next update. Sorry for taking a while, and let me know if you find something broken.
