### ISSUE TITLE
Square avatars won't show up?

### ISSUE THREAD

**Issue by Impeta** [Marda33/SkeuoCord#66]
![image](https://github.com/Marda33/SkeuoCord/assets/105376276/e16553fc-0946-4b80-a48e-2991d31877bf)

Didn't ever set the .css to turn on circle over square avatars. It also looks like the arrow pointing to you when you're replied is gone.

![image](https://github.com/Marda33/SkeuoCord/assets/105376276/d92d0e0d-46ae-42d0-a495-4c1fd451c2d5)

**Comment by LabRatMime** [comment]
This is happening with me as well.

**Comment by derpguy125** [comment]
There appear to be minor visual bugs with the most recent Discord update, should probably be fixed ASAP.
