### ISSUE TITLE
Lines on screen edges in fullscreen

### ISSUE THREAD

**Issue by elisenlebkuch** [Marda33/SkeuoCord#67]
![Screenshot_18:47_24-07-2024](https://github.com/user-attachments/assets/aab0cff7-25bc-482e-9d00-9de4e1d7a48f)
You can see them on any edge, though the one on the left side is much more visible than the ones on the other edges.

**Comment by Marda33** [comment]
The double line on the left edge has been fixed with the current version. The rest of the lines can't be removed in fullscreen as they make up the app window border.

**Comment by elisenlebkuch** [comment]
It's only fixed in dark mode.

**Comment by Marda33** [comment]
The current update also fixes the issue in light mode. Thanks for pointing that out.
