### ISSUE TITLE
Suggestion: Status's around the user profile border?

### ISSUE THREAD

**Issue by skyer1a** [Marda33/SkeuoCord#68]
![Discord_6dgQCPVC2S](https://github.com/user-attachments/assets/ee09e763-d412-4d74-a0cf-4f494b1deb70)
around the bordered square and not just hanging in the pfp?

**Comment by Marda33** [comment]
This theme should do what you're looking for:
https://betterdiscord.app/theme/RadialStatus
You can edit the theme to match the border radiuses of the square avatars as well (set rs-avatar-shape to 5%).
