### ISSUE TITLE
[Suggestion] Make status icons skeuomorphic and fix clipping

### ISSUE THREAD

**Issue by santacapra** [Marda33/SkeuoCord#72]
![image](https://github.com/user-attachments/assets/619d50ca-3900-4243-8cc4-2d05a4a057a9)

**Comment by Marda33** [comment]
Unfortunately the status icons can't be themed, I've tried many times before and failed. 
As for the clipping, that's just the way the avatar borders work since they don't conform to the mask that cuts into the image itself. Nothing can be done there.
