### ISSUE TITLE
[Bug] I don't think the Reactions tab is meant to look like this...

### ISSUE THREAD

**Issue by santacapra** [Marda33/SkeuoCord#75]
![image](https://github.com/user-attachments/assets/d58c08dd-91ef-4533-8bde-3eef7f5c2624)

**Comment by Marda33** [comment]
The usernames appear correctly on my end with BetterDiscord. Could this be an incompatibility with the client you're using?

**Comment by santacapra** [comment]
I'm using Vencord, it shouldn't be an issue, it isn't with any other themes..

**Comment by Marda33** [comment]
I've asked others using the theme with Vencord and they don't appear to have this issue. 
I've also just pushed an update, does it fix anything for you?

**Comment by santacapra** [comment]
I don't currently have the auto-update version, where can i get the update?

**Comment by Marda33** [comment]
As long as you got the theme through BetterDiscord or are using SkeuoCord.theme.css from this repo you have the auto update version. Disable and reenable the theme for the new version to load.

**Comment by Marda33** [comment]
Has the issue been fixed for you?

**Comment by santacapra** [comment]
![image](https://github.com/user-attachments/assets/b4d45c12-1f47-4f66-8c85-531f2966f05d)
It's still the same

**Comment by Marda33** [comment]
Are there other plugins/themes you're using alongside SkeuoCord? 
As I've said before other Vencord users reported no issues, so I think this could be a conflict with another plugin/theme.

**Comment by santacapra** [comment]
![image](https://github.com/user-attachments/assets/d0e5de27-59d2-4d85-ad48-5eb743e1b88d)
![image](https://github.com/user-attachments/assets/0eb7bbb4-dfc9-4811-a1ff-6a3c5899a053)

There are these, the only one directly related to reactions is WhoReacted, but disabling it didn't change anything

**Comment by santacapra** [comment]
I think I'll just use a different theme for now. Oh well

**Comment by Marda33** [comment]
Would you be able to send your Discord username so we can take a closer look? Sorry for going in and out, uni projects and Turkey's Discord block makes it hard to work on the theme consistently.

**Comment by santacapra** [comment]
Tamam bro and you're good :]

It's cloudsides

**Comment by Marda33** [comment]
This issue has been fixed in the latest version.
