### ISSUE TITLE
Chat loading screen doesn't fit on the theme

### ISSUE THREAD

**Issue by I-am-Sachi** [Marda33/SkeuoCord#78]
![image](https://github.com/user-attachments/assets/f6c64b6a-ce02-4830-b4c1-7af212bef629)
Can you transparentize the loading UI so I can see the background? It really doesn't fit.

**Comment by Marda33** [comment]
The new version should remove the background from the loading screen (Disable and reenable the theme to get it). Has it worked on your end?
